### ISSUE TITLE
cancle_period = 4h

### ISSUE THREAD

**Issue by angelsomar** [smoochy/WolfsOfCrypto#2]
Hello, again, congratulations to the team

It is necessary to be able to place indicators in periods of 4 hours

This only to determine general trends

![image](https://user-images.githubusercontent.com/36096512/40099266-ee679bae-58a4-11e8-8c89-19052ee998bc.png)

**Comment by smoochy** [comment]
Hey, thanks for reaching out.

Unfortunately TradingView does not offer a 4h candle period natively, hence it is not as easy to provide it.

We will discuss how we can achieve this. Please stay tuned.

**Comment by smoochy** [comment]
There is good news for you and all other lovers of sexy 4h candles. It will be in the next version of the script.
